# Zola configuration file for SkySplat.org

base_url = "https://skysplat.org"
title = "SkySplat"
description = "Professional 3D Gaussian Splatting (3DGS) tools for Blender. Transform drone footage into photorealistic 3D scenes using COLMAP, Brush, and cutting-edge Gaussian splatting technology."
default_language = "en"

# Compile Sass files
compile_sass = true

# Build search index for search functionality
build_search_index = true

# Generate RSS feed and sitemap for SEO
generate_feeds = true
feed_limit = 20

# Taxonomies (categories and tags)
taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[markdown]
# Enable syntax highlighting
highlight_code = true
highlight_theme = "base16-ocean-dark"

# Enable smart punctuation
smart_punctuation = true

[extra]
# Custom variables
author = "SkySplat Team"
github_username = "kyjohnso"
email = "your-email@example.com"

# Navigation menu
[[extra.menu]]
name = "Home"
url = "/"

[[extra.menu]]
name = "Blog"
url = "/blog/"

[[extra.menu]]
name = "Docs"
url = "/docs/"

[[extra.menu]]
name = "Articles"
url = "/articles/"

[[extra.menu]]
name = "About"
url = "/about/"